const SUPABASE_URL='https://fcuqketnfpvmjcaknasf.supabase.co';
const SUPABASE_KEY='sb_publishable_yoWJCM6XIpzJgKFu1tQWuQ_9CfxP1hv';
const ALLOWED_ADMIN='asifrahman1324@gmail.com';
const supabaseClient=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
async function boot(){const {data:{session}}=await supabaseClient.auth.getSession();if(session?.user?.email?.toLowerCase()===ALLOWED_ADMIN){showApp();return}if(session)await supabaseClient.auth.signOut()}
function showApp(){ $('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');loadAll() }
$('#loginForm').addEventListener('submit',async e=>{e.preventDefault();$('#loginError').textContent='';const {error}=await supabaseClient.auth.signInWithPassword({email:$('#email').value.trim(),password:$('#password').value});if(error){$('#loginError').textContent=error.message;return}const {data:{user}}=await supabaseClient.auth.getUser();if(user?.email?.toLowerCase()!==ALLOWED_ADMIN){await supabaseClient.auth.signOut();$('#loginError').textContent='This account is not authorized.';return}showApp()});
supabaseClient.auth.onAuthStateChange((_event,session)=>{if(!session)location.reload()});
$('#logout').addEventListener('click',async()=>{await supabaseClient.auth.signOut()});
document.querySelectorAll('.side-link').forEach(b=>b.addEventListener('click',()=>showSection(b.dataset.section)));
function showSection(id){document.querySelectorAll('.panel').forEach(p=>p.classList.toggle('active',p.id===id));document.querySelectorAll('.side-link').forEach(b=>b.classList.toggle('active',b.dataset.section===id));$('#pageTitle').textContent={dashboard:'Dashboard',service:'Service',orders:'Order',intro:'Intro',blog:'Blog',project:'Project'}[id]}
async function loadAll(){await Promise.all([loadServices(),loadOrders(),loadIntro(),loadBlogs(),loadProjects()])}
async function loadServices(){const {data,error}=await supabaseClient.from('services').select('*').order('created_at');if(error)return console.error(error);$('#statServices').textContent=data.length;$('#servicesList').innerHTML=data.length?data.map(x=>`<div class="item"><div><h3>${esc(x.name)}</h3><p>${esc(x.price)} · ${esc(x.description)}</p></div><div class="actions"><button class="small-btn" onclick="editService('${x.id}')">Edit</button><button class="small-btn danger" onclick="deleteRow('services','${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No services yet.</div>'}
async function editService(id){const {data}=await supabaseClient.from('services').select('*').eq('id',id).single();if(!data)return;const name=prompt('Service name',data.name);if(name===null)return;const price=prompt('Price',data.price);if(price===null)return;const description=prompt('Description',data.description||'');if(description===null)return;await supabaseClient.from('services').update({name,price,description}).eq('id',id);loadServices()}
$('#addService').addEventListener('click',async()=>{const name=prompt('Service name');if(!name)return;const price=prompt('Price');if(price===null)return;const description=prompt('Description')||'';await supabaseClient.from('services').insert({name,price,description});loadServices()});
async function loadOrders(){const {data,error}=await supabaseClient.from('orders').select('*').order('created_at',{ascending:false});if(error){console.error(error);return}$('#statOrders').textContent=data.length;$('#ordersList').innerHTML=data.length?`<table class="orders-table"><thead><tr><th>Customer</th><th>Service</th><th>Phone</th><th>Status</th><th>Action</th></tr></thead><tbody>${data.map(x=>`<tr><td>${esc(x.customer_name)}</td><td>${esc(x.service)}</td><td>${esc(x.phone)}</td><td>${esc(x.status)}</td><td><button class="small-btn" onclick="cycleOrder('${x.id}','${esc(x.status)}')">Update</button></td></tr>`).join('')}</tbody></table>`:'<div class="empty">No orders yet.</div>'}
async function cycleOrder(id,status){const states=['Pending','Confirmed','Completed','Cancelled'];const next=states[(states.indexOf(status)+1)%states.length];await supabaseClient.from('orders').update({status:next}).eq('id',id);loadOrders()}
async function loadIntro(){const {data,error}=await supabaseClient.from('intro_cards').select('*').order('id');if(error)return console.error(error);$('#introForm').innerHTML=data.map(x=>`<div class="form-block"><h3>${esc(x.section_key.toUpperCase())}</h3><label>Title<input data-id="${x.id}" data-field="title" value="${esc(x.title)}"></label><label>Description<textarea rows="4" data-id="${x.id}" data-field="description">${esc(x.description)}</textarea></label></div>`).join('')}
$('#saveIntro').addEventListener('click',async()=>{for(const el of document.querySelectorAll('#introForm [data-id]')){const id=el.dataset.id;const field=el.dataset.field;await supabaseClient.from('intro_cards').update({[field]:el.value,updated_at:new Date().toISOString()}).eq('id',id)};alert('Intro cards saved.');loadIntro()});
async function loadBlogs(){const {data,error}=await supabaseClient.from('blog_posts').select('*').order('created_at',{ascending:false});if(error)return console.error(error);$('#statBlogs').textContent=data.length;$('#blogsList').innerHTML=data.length?data.map(x=>`<div class="item"><div><h3>${esc(x.title)}</h3><p>${esc(x.description)} · ${x.published?'Published':'Draft'}</p></div><div class="actions"><button class="small-btn" onclick="editBlog('${x.id}')">Edit</button><button class="small-btn" onclick="togglePublish('blog_posts','${x.id}',${x.published})">${x.published?'Unpublish':'Publish'}</button><button class="small-btn danger" onclick="deleteRow('blog_posts','${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No blog posts yet.</div>'}
async function editBlog(id){const {data}=await supabaseClient.from('blog_posts').select('*').eq('id',id).single();if(!data)return;const title=prompt('Title',data.title);if(title===null)return;const description=prompt('Short description',data.description||'');if(description===null)return;const content=prompt('Content',data.content||'');if(content===null)return;await supabaseClient.from('blog_posts').update({title,description,content}).eq('id',id);loadBlogs()}
$('#addBlog').addEventListener('click',async()=>{const title=prompt('Title');if(!title)return;const description=prompt('Short description')||'';const content=prompt('Content')||'';await supabaseClient.from('blog_posts').insert({title,description,content,published:false});loadBlogs()});
async function loadProjects(){const {data,error}=await supabaseClient.from('projects').select('*').order('created_at',{ascending:false});if(error)return console.error(error);$('#statProjects').textContent=data.length;$('#projectsList').innerHTML=data.length?data.map(x=>`<div class="item"><div><h3>${esc(x.title)}</h3><p>${esc(x.description)} · ${x.published?'Published':'Draft'}</p></div><div class="actions"><button class="small-btn" onclick="editProject('${x.id}')">Edit</button><button class="small-btn" onclick="togglePublish('projects','${x.id}',${x.published})">${x.published?'Unpublish':'Publish'}</button><button class="small-btn danger" onclick="deleteRow('projects','${x.id}')">Delete</button></div></div>`).join(''):'<div class="empty">No projects yet.</div>'}
async function editProject(id){const {data}=await supabaseClient.from('projects').select('*').eq('id',id).single();if(!data)return;const title=prompt('Title',data.title);if(title===null)return;const description=prompt('Description',data.description||'');if(description===null)return;const content=prompt('Project details',data.content||'');if(content===null)return;await supabaseClient.from('projects').update({title,description,content}).eq('id',id);loadProjects()}
$('#addProject').addEventListener('click',async()=>{const title=prompt('Project title');if(!title)return;const description=prompt('Description')||'';const content=prompt('Project details')||'';await supabaseClient.from('projects').insert({title,description,content,published:false});loadProjects()});
async function togglePublish(table,id,value){await supabaseClient.from(table).update({published:!value}).eq('id',id);table==='blog_posts'?loadBlogs():loadProjects()}
async function deleteRow(table,id){if(!confirm('Delete this item?'))return;await supabaseClient.from(table).delete().eq('id',id);if(table==='services')loadServices();if(table==='blog_posts')loadBlogs();if(table==='projects')loadProjects()}
boot();