(function(){
const translations={
'Back':'ফিরে যান','All articles':'সব লেখা','All projects':'সব প্রজেক্ট','Get in Touch':'যোগাযোগ করুন','Work with me →':'আমার সাথে কাজ করুন →','View Pricing':'প্রাইসিং দেখুন','Chat on WhatsApp':'WhatsApp-এ কথা বলুন','Read article →':'আর্টিকেল পড়ুন →','View project overview →':'প্রজেক্ট ওভারভিউ দেখুন →','Discuss your business →':'আপনার ব্যবসা নিয়ে কথা বলুন →','Back to all articles':'সব লেখায় ফিরে যান','Back to all projects':'সব প্রজেক্টে ফিরে যান','Pricing':'প্রাইসিং','Blog':'ব্লগ','Project':'প্রজেক্ট','Intro':'পরিচিতি','All':'সব','Strategy':'স্ট্র্যাটেজি','Marketing':'মার্কেটিং','Digital':'ডিজিটাল','Entrepreneurship':'উদ্যোক্তা','Search articles...':'আর্টিকেল খুঁজুন...','THE GROWTH JOURNAL':'গ্রোথ জার্নাল','LATEST THINKING':'সাম্প্রতিক ভাবনা','From the journal':'জার্নাল থেকে','SELECTED WORK':'নির্বাচিত কাজ','Projects built to solve real problems.':'বাস্তব সমস্যার সমাধানে তৈরি প্রজেক্ট।','SERVICES':'সার্ভিসেস','Flexible consulting engagements built around your business stage and growth challenge.':'আপনার ব্যবসার অবস্থান ও গ্রোথ চ্যালেঞ্জ অনুযায়ী তৈরি নমনীয় কনসালটিং সেবা।','Business Consultant':'বিজনেস কনসালট্যান্ট','Helping businesses grow is what I do best and I can do the same for you.':'ব্যবসাকে গ্রো করতে সাহায্য করাই আমার কাজ—আপনার ব্যবসার জন্যও একইভাবে কাজ করতে পারি।'};
const original=new WeakMap();let lang=localStorage.getItem('siteLanguage')||'en';
function addStyles(){if(document.getElementById('language-style'))return;const s=document.createElement('style');s.id='language-style';s.textContent='.language-switcher{display:flex;align-items:center;margin-right:10px;padding:3px;border:1px solid rgba(255,255,255,.14);background:rgba(255,255,255,.055);border-radius:999px;gap:2px}.language-switcher button{border:0;background:transparent;color:rgba(255,255,255,.48);font:500 .63rem JetBrains Mono,monospace;padding:6px 9px;border-radius:999px;cursor:pointer}.language-switcher button.active{background:rgba(255,255,255,.12);color:#fff}.site-header .nav-cta{margin-left:0}.site-header{gap:10px}@media(max-width:760px){.site-header{display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:8px}.site-header .mobile-menu-btn{grid-column:1;grid-row:1;order:initial;margin:0;justify-self:start}.site-header .nav-cta{grid-column:3;grid-row:1;order:initial;margin:0;justify-self:end}.language-switcher{grid-column:2;grid-row:1;order:initial;margin:0;justify-self:end;margin-right:0}.language-switcher button{padding:6px 7px}}';document.head.appendChild(s)}
function walk(root){const nodes=[];const w=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(w.nextNode())nodes.push(w.currentNode);nodes.forEach(n=>{if(!original.has(n))original.set(n,n.nodeValue);const en=original.get(n).trim();if(!en)return;if(lang==='bn'&&translations[en]){n.nodeValue=n.nodeValue.replace(en,translations[en])}else if(lang==='en'&&translations[en]){n.nodeValue=n.nodeValue.replace(translations[en],en)}})}
function translate(){document.documentElement.lang=lang==='bn'?'bn':'en';walk(document.body);document.querySelectorAll('input[placeholder]').forEach(i=>{if(!i.dataset.enPlaceholder)i.dataset.enPlaceholder=i.placeholder;if(lang==='bn'&&translations[i.dataset.enPlaceholder])i.placeholder=translations[i.dataset.enPlaceholder];else i.placeholder=i.dataset.enPlaceholder});const btns=document.querySelectorAll('.language-switcher button');btns.forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));}
function setup(){addStyles();const c=document.createElement('div');c.className='language-switcher';c.setAttribute('aria-label','Choose language');c.innerHTML='<button type="button" data-lang="en">EN</button><button type="button" data-lang="bn">বাংলা</button>';const cta=document.querySelector('.site-header .nav-cta');if(cta)cta.parentNode.insertBefore(c,cta);c.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;lang=b.dataset.lang;localStorage.setItem('siteLanguage',lang);translate()});translate();new MutationObserver(()=>{if(lang==='bn')walk(document.body)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();
})();