/**
 * Md Asif Rahman - Interactive Scrollytelling Engine
 * 240 Frame Canvas Animation with Lerp Interpolation
 */
const TOTAL_FRAMES=240,FRAME_PATH_PREFIX='asifrahman-jpg/ezgif-frame-',FRAME_PATH_SUFFIX='.jpg',LERP_SPEED=.09;
let images=new Array(TOTAL_FRAMES+1),loadedFrames=new Set(),loadedCount=0,currentFrame=1,targetFrame=1,isAutoPlaying=false,autoPlaySpeed=.5,fitMode='cover',isAudioPlaying=false,audioContext=null,ambientGainNode=null;
const canvas=document.getElementById('animation-canvas'),ctx=canvas.getContext('2d'),preloader=document.getElementById('preloader'),preloaderFill=document.getElementById('preloader-fill'),preloaderPercent=document.getElementById('preloader-percent'),preloaderCounter=document.getElementById('preloader-counter'),frameDisplay=document.getElementById('current-frame-num'),scrubSlider=document.getElementById('scrub-slider'),playBtn=document.getElementById('btn-play'),fitBtn=document.getElementById('btn-fit'),audioBtn=document.getElementById('btn-audio'),fullscreenBtn=document.getElementById('btn-fullscreen'),toastNotice=document.getElementById('toast-notice'),toastMessage=document.getElementById('toast-message');
const storySections=[{id:'section-hero',start:1,end:50},{id:'section-essence',start:62,end:115},{id:'section-precision',start:128,end:178},{id:'section-connect',start:188,end:240}];
function getFramePath(i){return `${FRAME_PATH_PREFIX}${String(i).padStart(3,'0')}${FRAME_PATH_SUFFIX}`}
function resizeCanvas(){const dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;canvas.width=Math.floor(w*dpr);canvas.height=Math.floor(h*dpr);drawCurrentFrame(Math.round(currentFrame))}
function drawImageProp(c,img,x,y,w,h,ox=.5,oy=.32,mode='cover'){if(!img||!img.complete||!img.naturalWidth)return;const nw=img.naturalWidth,nh=img.naturalHeight,r=nw/nh;let dw=w,dh=h;if(mode==='contain'){if(w/h>r)dw=h*r;else dh=w/r}else{if(w/h<r)dw=h*r;else dh=w/r}const dx=x+(w-dw)*ox,dy=y+(h-dh)*oy;c.fillStyle='#08080a';c.fillRect(0,0,w,h);c.drawImage(img,dx,dy,dw,dh)}
function drawCurrentFrame(i){const clamped=Math.min(TOTAL_FRAMES,Math.max(1,i));let img=images[clamped];if(!img||!img.complete){let near=null,d=Infinity;for(const n of loadedFrames){const diff=Math.abs(n-clamped);if(diff<d){d=diff;near=n}}if(near)img=images[near]}if(img&&img.complete){const dpr=Math.min(devicePixelRatio||1,2);ctx.save();ctx.setTransform(dpr,0,0,dpr,0,0);drawImageProp(ctx,img,0,0,innerWidth,innerHeight,.5,.32,fitMode);ctx.restore()}}
function preloadFrames(){const first=new Image();first.src=getFramePath(1);first.onload=()=>{images[1]=first;loadedFrames.add(1);loadedCount++;drawCurrentFrame(1);checkLoadProgress()};for(let i=2;i<=TOTAL_FRAMES;i++){const img=new Image();img.src=getFramePath(i);img.onload=()=>{images[i]=img;loadedFrames.add(i);loadedCount++;checkLoadProgress()};img.onerror=()=>{loadedCount++;checkLoadProgress()}}}
function checkLoadProgress(){const p=Math.min(100,Math.round(loadedCount/TOTAL_FRAMES*100));preloaderFill.style.width=`${p}%`;preloaderPercent.textContent=`${p}%`;preloaderCounter.textContent=`${loadedCount} / ${TOTAL_FRAMES}`;if((loadedCount>=35||p>=80)&&!preloader.classList.contains('hidden'))setTimeout(()=>preloader.classList.add('hidden'),350)}
function updateUI(f){frameDisplay.textContent=String(f).padStart(3,'0');scrubSlider.value=f;storySections.forEach(s=>{const el=document.getElementById(s.id);if(el)el.classList.toggle('active',f>=s.start&&f<=s.end)})}
function animationLoop(){if(isAutoPlaying){targetFrame+=autoPlaySpeed;if(targetFrame>TOTAL_FRAMES)targetFrame=1;const max=document.documentElement.scrollHeight-innerHeight;scrollTo({top:(targetFrame-1)/(TOTAL_FRAMES-1)*max,behavior:'instant'})}else{const max=document.documentElement.scrollHeight-innerHeight,p=max>0?Math.min(1,Math.max(0,scrollY/max)):0;targetFrame=1+p*(TOTAL_FRAMES-1)}currentFrame+=(targetFrame-currentFrame)*LERP_SPEED;const f=Math.round(currentFrame);drawCurrentFrame(f);updateUI(f);requestAnimationFrame(animationLoop)}
function toggleMobileMenu(){const btn=document.getElementById('mobile-menu-btn'),nav=document.getElementById('main-nav');if(!btn||!nav)return;const open=btn.classList.toggle('open');nav.classList.toggle('mobile-open',open);btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'Close menu':'Open menu')}
function closeMobileMenu(){const btn=document.getElementById('mobile-menu-btn'),nav=document.getElementById('main-nav');if(btn&&nav){btn.classList.remove('open');nav.classList.remove('mobile-open');btn.setAttribute('aria-expanded','false');btn.setAttribute('aria-label','Open menu')}}
function initEvents(){addEventListener('resize',resizeCanvas);const menuBtn=document.getElementById('mobile-menu-btn');if(menuBtn)menuBtn.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();toggleMobileMenu()});document.querySelectorAll('#main-nav .nav-link').forEach(link=>link.addEventListener('click',()=>closeMobileMenu()));addEventListener('wheel',()=>{if(isAutoPlaying)toggleAutoPlay(false)},{passive:true});addEventListener('touchstart',()=>{if(isAutoPlaying)toggleAutoPlay(false)},{passive:true});scrubSlider.addEventListener('input',e=>{const f=parseInt(e.target.value,10),max=document.documentElement.scrollHeight-innerHeight;if(isAutoPlaying)toggleAutoPlay(false);scrollTo({top:(f-1)/(TOTAL_FRAMES-1)*max,behavior:'instant'});targetFrame=f});playBtn.addEventListener('click',()=>toggleAutoPlay(!isAutoPlaying));fitBtn.addEventListener('click',()=>{fitMode=fitMode==='cover'?'contain':'cover';fitBtn.classList.toggle('active',fitMode==='contain');showToast(fitMode==='contain'?'Display Mode: Original 16:9 Letterbox':'Display Mode: Fullscreen Cinematic Cover');drawCurrentFrame(Math.round(currentFrame))});fullscreenBtn.addEventListener('click',()=>{if(!document.fullscreenElement){document.documentElement.requestFullscreen().catch(()=>{});fullscreenBtn.classList.add('active')}else{document.exitFullscreen().catch(()=>{});fullscreenBtn.classList.remove('active')}});audioBtn.addEventListener('click',toggleAmbientSound);document.querySelectorAll('[data-scroll-target]').forEach(link=>link.addEventListener('click',e=>{e.preventDefault();const s=storySections.find(x=>x.id===link.getAttribute('data-scroll-target'));if(s){const mid=Math.round((s.start+s.end)/2),max=document.documentElement.scrollHeight-innerHeight;scrollTo({top:(mid-1)/(TOTAL_FRAMES-1)*max,behavior:'smooth'})}}));addEventListener('keydown',e=>{if(e.target.tagName==='INPUT'||e.target.tagName==='TEXTAREA')return;if(e.code==='Space'){e.preventDefault();toggleAutoPlay(!isAutoPlaying)}else if(e.code==='ArrowRight'||e.code==='ArrowDown'){e.preventDefault();if(isAutoPlaying)toggleAutoPlay(false);const f=Math.min(TOTAL_FRAMES,targetFrame+4),max=document.documentElement.scrollHeight-innerHeight;scrollTo({top:(f-1)/(TOTAL_FRAMES-1)*max,behavior:'smooth'})}else if(e.code==='ArrowLeft'||e.code==='ArrowUp'){e.preventDefault();if(isAutoPlaying)toggleAutoPlay(false);const f=Math.max(1,targetFrame-4),max=document.documentElement.scrollHeight-innerHeight;scrollTo({top:(f-1)/(TOTAL_FRAMES-1)*max,behavior:'smooth'})}else if(e.key.toLowerCase()==='f')fullscreenBtn.click();else if(e.key.toLowerCase()==='m')audioBtn.click()})}
function toggleAutoPlay(state){isAutoPlaying=state;playBtn.classList.toggle('active',state);showToast(state?'Auto-play started (Space to pause)':'Auto-play paused')}
function toggleAmbientSound(){if(!isAudioPlaying){try{const A=AudioContext||webkitAudioContext;audioContext=new A;ambientGainNode=audioContext.createGain();ambientGainNode.gain.setValueAtTime(.001,audioContext.currentTime);ambientGainNode.gain.exponentialRampToValueAtTime(.12,audioContext.currentTime+2.5);ambientGainNode.connect(audioContext.destination);const o1=audioContext.createOscillator(),o2=audioContext.createOscillator(),filter=audioContext.createBiquadFilter();o1.type='sine';o1.frequency.value=110;o2.type='triangle';o2.frequency.value=164.81;filter.type='lowpass';filter.frequency.value=260;o1.connect(filter);o2.connect(filter);filter.connect(ambientGainNode);o1.start();o2.start();isAudioPlaying=true;audioBtn.classList.add('active');showToast('Ambient Atmosphere: Active')}catch(e){showToast('Audio unavailable')}}else{if(ambientGainNode&&audioContext){ambientGainNode.gain.exponentialRampToValueAtTime(.0001,audioContext.currentTime+.6);setTimeout(()=>{if(audioContext&&audioContext.state!=='closed')audioContext.close()},700)}isAudioPlaying=false;audioBtn.classList.remove('active');showToast('Atmosphere Muted')}}
let toastTimeout;function showToast(msg){clearTimeout(toastTimeout);toastMessage.textContent=msg;toastNotice.classList.add('show');toastTimeout=setTimeout(()=>toastNotice.classList.remove('show'),2400)}
addEventListener('DOMContentLoaded',()=>{resizeCanvas();preloadFrames();initEvents();animationLoop()});